### ISSUE TITLE
Not able to produce the results

### ISSUE THREAD

**Issue by h-aboutalebi** [NVlabs/FreeSOLO#10]
Hi,

When I run `bash test.sh {MODEL_PATH}`  and passing the weights of the downloaded trained model, I get the following error:

> Loading and preparing results...
Traceback (most recent call last):
  File "tools/eval_cocoapi.py", line 21, in <module>
    cocoDt=cocoGt.loadRes(resFile)
  File "python3.7/site-packages/pycocotools/coco.py", line 319, in loadRes
    with open(resFile) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'training_dir/FreeSOLO_pl/inference/coco_instances_results.json'

**Comment by ShaanSinghGill** [comment]
I am getting the same thing as well, even when I make a empty coco_instances_results.json. Are we supposed to download a file or something for this script?
